# this notebook contains practice on numpy arrays

In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a = np.array([11, 22, 33, 44, 55])
a

array([11, 22, 33, 44, 55])

In [4]:
np.__version__

'1.23.4'

In [5]:
a

array([11, 22, 33, 44, 55])

In [6]:
print(a)

[11 22 33 44 55]


In [7]:
type(a)

numpy.ndarray

In [10]:
c = [11, 22, 33, 44, 55]
print(type(c))
d = np.array(c)
print(type(d))

<class 'list'>
<class 'numpy.ndarray'>


In [19]:
a = np.array(43)
type(a)

numpy.ndarray

In [20]:
a.ndim

0

In [22]:
# 1 dimension array
a = np.array([22, 55, 66])
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
1


In [23]:
c = np.array([2])
print(type(c))
print(c.ndim)

<class 'numpy.ndarray'>
1


In [25]:
# 2 dimension array
e = np.array([[11,22],[33,44]])
print(e)
print(type(e))
print(e.ndim)

[[11 22]
 [33 44]]
<class 'numpy.ndarray'>
2


In [27]:
# 3 dimension array
f = np.array([[[11,22],[33,44]],[[55,66],[77,88]]])
print(f)
print(type(f))
print(f.ndim)

[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]
<class 'numpy.ndarray'>
3


In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [30]:
g = np.array([11, 22, 33, 44], ndmin=6)
print(g)
print(type(g))
print(g.ndim)

[[[[[[11 22 33 44]]]]]]
<class 'numpy.ndarray'>
6
