# this notebook contains practice on numpy arrays

In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a = np.array([11, 22, 33, 44, 55])
a

array([11, 22, 33, 44, 55])

In [4]:
np.__version__

'1.23.4'

In [5]:
a

array([11, 22, 33, 44, 55])

In [6]:
print(a)

[11 22 33 44 55]


In [7]:
type(a)

numpy.ndarray

In [10]:
c = [11, 22, 33, 44, 55]
print(type(c))
d = np.array(c)
print(type(d))

<class 'list'>
<class 'numpy.ndarray'>


In [19]:
a = np.array(43)
type(a)

numpy.ndarray

In [20]:
a.ndim

0

In [22]:
# 1 dimension array
a = np.array([22, 55, 66])
print(type(a))
print(a.ndim)

<class 'numpy.ndarray'>
1


In [23]:
c = np.array([2])
print(type(c))
print(c.ndim)

<class 'numpy.ndarray'>
1


In [25]:
# 2 dimension array
e = np.array([[11,22],[33,44]])
print(e)
print(type(e))
print(e.ndim)

[[11 22]
 [33 44]]
<class 'numpy.ndarray'>
2


In [27]:
# 3 dimension array
f = np.array([[[11,22],[33,44]],[[55,66],[77,88]]])
print(f)
print(type(f))
print(f.ndim)

[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]
<class 'numpy.ndarray'>
3


In [28]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [30]:
g = np.array([11, 22, 33, 44], ndmin=6)
print(g)
print(type(g))
print(g.ndim)

[[[[[[11 22 33 44]]]]]]
<class 'numpy.ndarray'>
6


In [53]:
import numpy as np

arr = np.array([[[1, 2, 3], 
                [4, 5, 6]],
                [[7, 8, 9], 
                 [10, 11, 12]]
               ])

# print(arr)
# print(arr[0, 1, 2])
# print(arr.ndim)
arr[0, 1, 2]

6

In [20]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 0])

10


ever in doudth, run the code

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [24]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [30]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [31]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 0:2])

[6 7]


In [35]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 0:3])

[1 2 3]


In [38]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 3:5])

[4 5]


In [58]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])

print(arr[0:2, 3])
# print(arr.ndim)

[4 9]


In [60]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], 
                [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Data types

In [1]:
import numpy as np

arr = np.array([11,22,33,44])
arr.dtype

dtype('int32')

In [2]:
arr1 = np.array(['a'])
arr1.dtype

dtype('<U1')

In [4]:
arr2 = np.array(['abd', 'abc', 'abc vision' ])
arr2.dtype

dtype('<U10')

In [5]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [13]:
arr = np.array([1.1, 2.1, 3.1, 64/3])
print(arr.dtype)

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

float64
[ 1  2  3 21]
int32


In [14]:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [15]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [30]:
arr[:][:][:][:][:]

array([[[[[1, 2, 3, 4]]]]])

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print(arr.shape)

newarr = arr.reshape(4, 3)

print(newarr)
print(newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print(arr.shape)
newarr = arr.reshape(3, 3, 2)

print(newarr)
print(newarr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


ValueError: cannot reshape array of size 12 into shape (3,3,2)

In [52]:
arr = np.array(range(49), ndmin=3)
print(arr.shape)

# to decide the number of matrix, no. of columns and number of rows for reshape,
# make sure the multiplication equals the number of all elements in the initial array.
# multiplication of (dimensions) or (no. of matrix * no. of rows * no. of columns)
newarr = arr.reshape(1,7,7)
print(newarr)
print(newarr.shape)
print(newarr.ndim)

(1, 1, 49)
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]
  [14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]
  [28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]
  [42 43 44 45 46 47 48]]]
(1, 7, 7)
3


### task: learn about copy and view in array + array interation